#index:
#    path: /
#    controller: App\Controller\DefaultController::index


# the "app_lucky_number" route name is not important yet
app_lucky_number:
  path: /lucky/number
  controller: App\Controller\LuckyController::number

apiCreateMobileDevice:
  path:                       /registerMobileDevice
  defaults:                   { _controller: App\Controller\Api\MobileDeviceController:createAction }
  methods:                    [POST]

#apiCreateGpsMobileDevice:
#  path:                       /gpsMobileDevice
#  defaults:                   { _controller: App\Controller\Api\MobileDeviceController:createGpsAction }
#  methods:                    [POST]